name: Build and Release

on:
  release:
    types:
      - published 

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: "tres-pack-helper-${{ github.event.release.tag_name }}"
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mkdir -v -p ~/.config/
        mv /root/.config/godot ~/.config/godot
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        git config --global --add safe.directory /__w/Tres-Pack-Helper/Tres-Pack-Helper # Fix detected dubious ownership.
    
    - name: Inject version into export preset
      run: |
        sed -i'.bak'  "s/\$VERSION/${{ github.event.release.tag_name }}/" export_presets.cfg

    - name: Windows Build
      run: |
        mkdir -v -p build/windows
        EXPORT_DIR="$(readlink -f build)"
        cd $PROJECT_PATH
        godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"

    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0
      with:
        gh-cli-version: 2.64.0 

    - name: Upload to release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} build/windows/*

  export-mac:
    name: MacOS Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates/
        mkdir -v -p ~/.config/
        mv /root/.config/godot ~/.config/godot
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        git config --global --add safe.directory /__w/Tres-Pack-Helper/Tres-Pack-Helper # Fix detected dubious ownership.
    
    - name: Inject version into export preset
      run: |
        sed -i'.bak'  "s/\$VERSION/${{ github.event.release.tag_name }}/" export_presets.cfg

    - name: MacOS Build
      run: |
        mkdir -v -p build/mac
        EXPORT_DIR="$(readlink -f build)"
        cd $PROJECT_PATH
        godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"

    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0
      with:
        gh-cli-version: 2.64.0 

    - name: Upload to release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} build/mac/*

        