name: Build and Release

on:
  release:
    types:
      - published 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux, windows, mac]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      id: build
      uses: manleydev/build-godot-action@v1.4.1
      with:
        name: "Tres Pack Helper ${{ github.event.release.tag_name }} (${{ matrix.platform }})"
        preset: ${{ matrix.platform }}

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/${{ steps.build.outputs.build }}

        